name: ZMK Firmware

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring

jobs:
  convert-and-store-keymap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: cat "$GITHUB_WORKSPACE/config/charybdis.keymap"
      - uses: actions/upload-artifact@v4
        with:
          name: keymap_files
          path: ${{ github.workspace }}/config/*.keymap

  build:
    uses: ./.github/workflows/user_config_build.yaml
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml
    # credit to https://github.com/caksoylar/keymap-drawer
